### PR TITLE
Fixes #63, adds Elise to the team section

### LINKED ISSUE #63: Add Elise to the team section
ping @EliseFitz15 😄

### PR DESCRIPTION
**Pull request by EliseFitz15**
image

### CODE REVIEW

**Comment by vikram7** [comment]
Awesome! Can you add a screenshot of what the new page looks like to your PR description?

**Comment by HeroicEric** [comment]
Looks like your git config is using an email that you don't have registered on github, so your commit doesn't show up as connected to your GitHub account.

While you could add your greenfield email to your GitHub account, I'd recommend using your personal email so GitHub doesn't ever [eat your Résumé](http://bikeshed.fm/35)

https://help.github.com/articles/setting-your-email-in-git/

**Comment by EliseFitz15** [comment]
Sure @vikram7 - added screenshot above. And Thanks for sharing that @HeroicEric, removed the other email.

**Comment by vikram7** [comment]
spacehship1

**Pull request merged**
